# Generated by Django 5.2.4 on 2025-10-04 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pollutant_type', models.CharField(choices=[('PM2.5', 'PM2.5'), ('PM10', 'PM10'), ('NO2', 'Nitrogen Dioxide'), ('SO2', 'Sulfur Dioxide'), ('CO', 'Carbon Monoxide'), ('O3', 'Ozone')], max_length=10)),
                ('predicted_concentration', models.FloatField()),
                ('predicted_aqi', models.IntegerField()),
                ('confidence_score', models.FloatField()),
                ('prediction_horizon_hours', models.IntegerField()),
                ('model_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prediction_for', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AirQualityReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pollutant_type', models.CharField(choices=[('PM2.5', 'PM2.5'), ('PM10', 'PM10'), ('NO2', 'Nitrogen Dioxide'), ('SO2', 'Sulfur Dioxide'), ('CO', 'Carbon Monoxide'), ('O3', 'Ozone')], max_length=10)),
                ('concentration', models.FloatField()),
                ('aqi_value', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('source', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['location', '-timestamp'], name='dashboard_a_locatio_540d6e_idx'), models.Index(fields=['pollutant_type', '-timestamp'], name='dashboard_a_polluta_dae114_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserLocationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('is_primary', models.BooleanField(default=False)),
                ('alert_threshold', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'location_name')},
            },
        ),
    ]
